const books = [
  {
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    bookNumber: "1",
    genre: "Classic Fiction",
    publishedYear: 1925,
    availabilityStatus: "Available",
    coverImageUrl: "https://covers.openlibrary.org/b/id/7222246-L.jpg",
  },
  {
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    bookNumber: "2",
    genre: "Classic Fiction",
    publishedYear: 1960,
    availabilityStatus: "Checked Out",
    coverImageUrl: "https://covers.openlibrary.org/b/id/8228691-L.jpg",
  },
  {
    title: "1984",
    author: "George Orwell",
    bookNumber: "3",
    genre: "Dystopian",
    publishedYear: 1949,
    availabilityStatus: "Available",
    coverImageUrl: "https://covers.openlibrary.org/b/id/153541-L.jpg",
  },
  {
    title: "The Alchemist",
    author: "Paulo Coelho",
    bookNumber: "4",
    genre: "Adventure",
    publishedYear: 1988,
    availabilityStatus: "Available",
    coverImageUrl: "https://covers.openlibrary.org/b/id/8108696-L.jpg",
  },
  {
    title: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    bookNumber: "5",
    genre: "History",
    publishedYear: 2011,
    availabilityStatus: "Checked Out",
    coverImageUrl: "https://covers.openlibrary.org/b/id/8774991-L.jpg",
  },
  {
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    bookNumber: "6",
    genre: "Young Adult",
    publishedYear: 1951,
    availabilityStatus: "Available",
    coverImageUrl: "https://covers.openlibrary.org/b/id/8225631-L.jpg",
  },
  {
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    bookNumber: "7",
    genre: "Fantasy",
    publishedYear: 1937,
    availabilityStatus: "Available",
    coverImageUrl: "https://covers.openlibrary.org/b/id/8108698-L.jpg",
  },
  {
    title: "Becoming",
    author: "Michelle Obama",
    bookNumber: "8",
    genre: "Autobiography",
    publishedYear: 2018,
    availabilityStatus: "Checked Out",
    coverImageUrl: "https://covers.openlibrary.org/b/id/9253448-L.jpg",
  },
  {
    title: "Atomic Habits",
    author: "James Clear",
    bookNumber: "9",
    genre: "Self-help",
    publishedYear: 2018,
    availabilityStatus: "Available",
    coverImageUrl: "https://covers.openlibrary.org/b/id/9644266-L.jpg",
  },
  {
    title: "Educated",
    author: "Tara Westover",
    bookNumber: "10",
    genre: "Memoir",
    publishedYear: 2018,
    availabilityStatus: "Available",
    coverImageUrl: "",
  }
];

export default books;